/* ipa-data.js — pronunciation data for the converter.
 *
 * Two data sources, tried in this order:
 *   1. LEXICON  — hand-written entries for words English spelling lies about.
 *   2. RULES    — ordered letter-to-sound rules (Elovitz et al., NRL 1976 set,
 *                 adapted to ARPAbet + a few additions).
 *
 * Phonemes are ARPAbet-ish. Two non-standard symbols:
 *   Q  = the LOT vowel (short o).  Kept apart from AA so British "lot" can be
 *        ɒ while "father" stays ɑː.
 *   AX = schwa.        IX = reduced ɪ.
 * A trailing 1 on a vowel in the LEXICON marks primary stress.
 *
 * Rule syntax:  LEFT[MATCH]RIGHT=PHONEMES
 *   #  one or more vowels (AEIOUY)      :  zero or more consonants
 *   ^  one consonant                    .  one voiced consonant (BDVGJLMNRWZ)
 *   +  one front vowel (E I Y)          &  a sibilant (S C G Z X J CH SH)
 *   @  a consonant after which long U is "oo" not "yoo" (T S R D L Z N J TH CH)
 *   %  a suffix (E ES ED ER ING ELY)    ' ' a word boundary
 * Empty PHONEMES means the letters are silent.
 */
(function (root) {
  'use strict';

  // ---------------------------------------------------------------- lexicon
  // Irregulars, function words, and anything the rules reliably mangle.
  var LEXICON = {
    // Function words. a/an/the/of default to their weak forms — in running
    // text those are what people actually say; WEAK below reduces the rest.
    a: 'AX', an: 'AX N', the: 'DH AX', of: 'AX V', to: 'T UW1',
    and: 'AE1 N D', or: 'AO1 R', but: 'B AH1 T', for: 'F AO1 R',
    from: 'F R AH1 M', with: 'W IH1 DH', as: 'AE1 Z', at: 'AE1 T',
    by: 'B AY1', in: 'IH1 N', into: 'IH1 N T UW', on: 'AA1 N',
    is: 'IH1 Z', are: 'AA1 R', was: 'W AH1 Z', were: 'W ER1',
    be: 'B IY1', been: 'B IH1 N', being: 'B IY1 IH NG', am: 'AE1 M',
    he: 'HH IY1', she: 'SH IY1', we: 'W IY1', me: 'M IY1', you: 'Y UW1',
    they: 'DH EY1', them: 'DH EH1 M', their: 'DH EH1 R', there: 'DH EH1 R',
    theirs: 'DH EH1 R Z', these: 'DH IY1 Z', those: 'DH OW1 Z',
    this: 'DH IH1 S', that: 'DH AE1 T', than: 'DH AE1 N', then: 'DH EH1 N',
    though: 'DH OW1', thus: 'DH AH1 S', his: 'HH IH1 Z', her: 'HH ER1',
    hers: 'HH ER1 Z', him: 'HH IH1 M', its: 'IH1 T S', our: 'AW1 ER',
    your: 'Y AO1 R', who: 'HH UW1', whom: 'HH UW1 M', whose: 'HH UW1 Z',
    what: 'W AH1 T', where: 'W EH1 R', when: 'W EH1 N', why: 'W AY1',
    which: 'W IH1 CH', while: 'W AY1 L', would: 'W UH1 D',
    could: 'K UH1 D', should: 'SH UH1 D', shall: 'SH AE1 L',
    will: 'W IH1 L', can: 'K AE1 N', must: 'M AH1 S T', may: 'M EY1',
    have: 'HH AE1 V', has: 'HH AE1 Z', had: 'HH AE1 D',
    do: 'D UW1', does: 'D AH1 Z', did: 'D IH1 D', done: 'D AH1 N',
    go: 'G OW1', goes: 'G OW1 Z', gone: 'G AO1 N', going: 'G OW1 IH NG',
    say: 'S EY1', says: 'S EH1 Z', said: 'S EH1 D',
    one: 'W AH1 N', once: 'W AH1 N S', two: 'T UW1', four: 'F AO1 R',
    eight: 'EY1 T', none: 'N AH1 N', only: 'OW1 N L IY',
    some: 'S AH1 M', something: 'S AH1 M TH IH NG', someone: 'S AH1 M W AH N',
    any: 'EH1 N IY', anything: 'EH1 N IY TH IH NG', many: 'M EH1 N IY',
    very: 'V EH1 R IY', every: 'EH1 V R IY', again: 'AX G EH1 N',
    against: 'AX G EH1 N S T', because: 'B IH K AO1 Z', about: 'AX B AW1 T',
    above: 'AX B AH1 V', other: 'AH1 DH ER', another: 'AX N AH1 DH ER',
    over: 'OW1 V ER', after: 'AE1 F T ER', before: 'B IH F AO1 R',
    through: 'TH R UW1', thorough: 'TH ER1 OW', enough: 'IH N AH1 F',
    both: 'B OW1 TH', how: 'HH AW1', now: 'N AW1', here: 'HH IY1 R',
    hear: 'HH IY1 R', near: 'N IY1 R', year: 'Y IY1 R',
    always: 'AO1 L W EY Z', also: 'AO1 L S OW', almost: 'AO1 L M OW S T',
    upon: 'AX P AA1 N', until: 'AH N T IH1 L', without: 'W IH DH AW1 T',

    // contractions
    "don't": 'D OW1 N T', "won't": 'W OW1 N T', "can't": 'K AE1 N T',
    "isn't": 'IH1 Z AX N T', "aren't": 'AA1 R N T', "wasn't": 'W AH1 Z AX N T',
    "weren't": 'W ER1 N T', "doesn't": 'D AH1 Z AX N T',
    "didn't": 'D IH1 D AX N T', "hasn't": 'HH AE1 Z AX N T',
    "haven't": 'HH AE1 V AX N T', "hadn't": 'HH AE1 D AX N T',
    "couldn't": 'K UH1 D AX N T', "wouldn't": 'W UH1 D AX N T',
    "shouldn't": 'SH UH1 D AX N T', "ain't": 'EY1 N T',
    "i'm": 'AY1 M', "i've": 'AY1 V', "i'll": 'AY1 L', "i'd": 'AY1 D',
    "you're": 'Y UH1 R', "you've": 'Y UW1 V', "you'll": 'Y UW1 L',
    "you'd": 'Y UW1 D', "we're": 'W IY1 R', "we've": 'W IY1 V',
    "we'll": 'W IY1 L', "we'd": 'W IY1 D', "they're": 'DH EH1 R',
    "they've": 'DH EY1 V', "they'll": 'DH EY1 L', "they'd": 'DH EY1 D',
    "it's": 'IH1 T S', "that's": 'DH AE1 T S', "what's": 'W AH1 T S',
    "there's": 'DH EH1 R Z', "here's": 'HH IY1 R Z', "let's": 'L EH1 T S',
    "he's": 'HH IY1 Z', "she's": 'SH IY1 Z', "who's": 'HH UW1 Z',
    "i": 'AY1',

    // silent letters & spelling traps
    island: 'AY1 L AX N D', isle: 'AY1 L', aisle: 'AY1 L',
    iron: 'AY1 ER N', hour: 'AW1 ER', honest: 'AA1 N AX S T',
    honour: 'AA1 N ER', honor: 'AA1 N ER', heir: 'EH1 R',
    debt: 'D EH1 T', doubt: 'D AW1 T', subtle: 'S AH1 T AX L',
    receipt: 'R IH S IY1 T', corps: 'K AO1 R', colonel: 'K ER1 N AX L',
    yacht: 'Y AA1 T', choir: 'K W AY1 ER', sword: 'S AO1 R D',
    answer: 'AE1 N S ER', castle: 'K AE1 S AX L', listen: 'L IH1 S AX N',
    often: 'AO1 F AX N', whistle: 'W IH1 S AX L', wrestle: 'R EH1 S AX L',
    knee: 'N IY1', knife: 'N AY1 F', knight: 'N AY1 T', knock: 'N AA1 K',
    know: 'N OW1', known: 'N OW1 N', knowledge: 'N AA1 L IH JH',
    gnome: 'N OW1 M', psalm: 'S AA1 M', pseudo: 'S UW1 D OW',
    psyche: 'S AY1 K IY', psychology: 'S AY K AA1 L AX JH IY',
    rhythm: 'R IH1 DH AX M', asthma: 'AE1 Z M AX', salmon: 'S AE1 M AX N',
    wednesday: 'W EH1 N Z D EY', february: 'F EH1 B R UW EH R IY',
    business: 'B IH1 Z N AX S', comfortable: 'K AH1 M F T ER B AX L',
    vegetable: 'V EH1 JH T AX B AX L', chocolate: 'CH AO1 K L AX T',
    restaurant: 'R EH1 S T R AA N T', temperature: 'T EH1 M P R AX CH ER',
    interesting: 'IH1 N T R AX S T IH NG', favourite: 'F EY1 V R IH T',
    favorite: 'F EY1 V R IH T', chocolatey: 'CH AO1 K L AX T IY',
    women: 'W IH1 M IH N', woman: 'W UH1 M AX N', people: 'P IY1 P AX L',
    minute: 'M IH1 N IH T', second: 'S EH1 K AX N D', biscuit: 'B IH1 S K IH T',
    circuit: 'S ER1 K IH T', tortoise: 'T AO1 R T AX S',
    laugh: 'L AE1 F', laughed: 'L AE1 F T', laughter: 'L AE1 F T ER',
    rough: 'R AH1 F', tough: 'T AH1 F', cough: 'K AO1 F', trough: 'T R AO1 F',
    dough: 'D OW1', bough: 'B AW1', plough: 'P L AW1',
    thought: 'TH AO1 T', bought: 'B AO1 T', brought: 'B R AO1 T',
    caught: 'K AO1 T', taught: 'T AO1 T', daughter: 'D AO1 T ER',
    height: 'HH AY1 T', weight: 'W EY1 T', neighbour: 'N EY1 B ER',
    neighbor: 'N EY1 B ER', straight: 'S T R EY1 T',
    sign: 'S AY1 N', design: 'D IH Z AY1 N', assign: 'AX S AY1 N',
    foreign: 'F AO1 R IH N', sovereign: 'S AA1 V R IH N',
    friend: 'F R EH1 N D', guest: 'G EH1 S T', guess: 'G EH1 S',
    guide: 'G AY1 D', guilty: 'G IH1 L T IY', guitar: 'G IH T AA1 R',
    tongue: 'T AH1 NG', league: 'L IY1 G', vague: 'V EY1 G',
    unique: 'Y UW N IY1 K', antique: 'AE N T IY1 K', queue: 'K Y UW1',
    busy: 'B IH1 Z IY', bury: 'B EH1 R IY', buoy: 'B UW1 IY',
    build: 'B IH1 L D', built: 'B IH1 L T', suite: 'S W IY1 T',

    // <ch>, <s>, <t> that misbehave
    ache: 'EY1 K', school: 'S K UW1 L', scheme: 'S K IY1 M',
    chorus: 'K AO1 R AX S', chaos: 'K EY1 AA S', character: 'K EH1 R IH K T ER',
    stomach: 'S T AH1 M AX K', echo: 'EH1 K OW', anchor: 'AE1 NG K ER',
    machine: 'M AX SH IY1 N', chef: 'SH EH1 F', chic: 'SH IY1 K',
    mustache: 'M AH1 S T AE SH', ocean: 'OW1 SH AX N',
    sure: 'SH UH1 R', sugar: 'SH UH1 G ER', issue: 'IH1 SH UW',
    measure: 'M EH1 ZH ER', pleasure: 'P L EH1 ZH ER',
    treasure: 'T R EH1 ZH ER', vision: 'V IH1 ZH AX N',
    usual: 'Y UW1 ZH UW AX L', casual: 'K AE1 ZH UW AX L',
    genre: 'ZH AA1 N R AX', beige: 'B EY1 ZH', garage: 'G AX R AA1 ZH',
    massage: 'M AX S AA1 ZH', judge: 'JH AH1 JH', orange: 'AO1 R IH N JH',
    ancient: 'EY1 N SH AX N T', special: 'S P EH1 SH AX L',
    precious: 'P R EH1 SH AX S', question: 'K W EH1 S CH AX N',
    picture: 'P IH1 K CH ER', nature: 'N EY1 CH ER', future: 'F Y UW1 CH ER',
    science: 'S AY1 AX N S', scissors: 'S IH1 Z ER Z',

    // <ea> / <ou> / <o> traps
    bread: 'B R EH1 D', head: 'HH EH1 D', dead: 'D EH1 D',
    read: 'R IY1 D', great: 'G R EY1 T', break: 'B R EY1 K',
    steak: 'S T EY1 K', heart: 'HH AA1 R T', earth: 'ER1 TH',
    early: 'ER1 L IY', learn: 'L ER1 N', heard: 'HH ER1 D',
    world: 'W ER1 L D', word: 'W ER1 D', work: 'W ER1 K',
    worse: 'W ER1 S', worth: 'W ER1 TH', journey: 'JH ER1 N IY',
    love: 'L AH1 V', move: 'M UW1 V', prove: 'P R UW1 V',
    come: 'K AH1 M', become: 'B IH K AH1 M', glove: 'G L AH1 V',
    lose: 'L UW1 Z', close: 'K L OW1 S', whole: 'HH OW1 L',
    door: 'D AO1 R', floor: 'F L AO1 R', poor: 'P UH1 R', tour: 'T UH1 R',
    mother: 'M AH1 DH ER', father: 'F AA1 DH ER', brother: 'B R AH1 DH ER',
    water: 'W AO1 T ER', money: 'M AH1 N IY', monkey: 'M AH1 NG K IY',
    country: 'K AH1 N T R IY', young: 'Y AH1 NG', touch: 'T AH1 CH',
    couple: 'K AH1 P AX L', trouble: 'T R AH1 B AX L', double: 'D AH1 B AX L',
    blood: 'B L AH1 D', flood: 'F L AH1 D', wolf: 'W UH1 L F',
    put: 'P UH1 T', push: 'P UH1 SH', pull: 'P UH1 L', full: 'F UH1 L',
    live: 'L IH1 V', give: 'G IH1 V',

    // vowel-heavy loanwords & everyday polysyllables
    idea: 'AY D IY1 AX', area: 'EH1 R IY AX', create: 'K R IY EY1 T',
    real: 'R IY1 L', really: 'R IY1 L IY', hero: 'HH IY1 R OW',
    zero: 'Z IY1 R OW', video: 'V IH1 D IY OW', radio: 'R EY1 D IY OW',
    piano: 'P IY AE1 N OW', pizza: 'P IY1 T S AX', karaoke: 'K EH R IY OW1 K IY',
    cafe: 'K AE F EY1', ballet: 'B AE L EY1', buffet: 'B AX F EY1',
    debut: 'D EY B Y UW1', bouquet: 'B OW K EY1', gourmet: 'G AO R M EY1',
    colour: 'K AH1 L ER', color: 'K AH1 L ER', example: 'IH G Z AE1 M P AX L',
    beautiful: 'B Y UW1 T IH F AX L', beauty: 'B Y UW1 T IY',
    language: 'L AE1 NG G W IH JH', english: 'IH1 NG G L IH SH',
    phonetics: 'F AX N EH1 T IH K S', phonetic: 'F AX N EH1 T IH K',
    alphabet: 'AE1 L F AX B EH T', pronounce: 'P R AX N AW1 N S',
    pronunciation: 'P R AX N AH N S IY EY1 SH AX N',
    transcription: 'T R AE N S K R IH1 P SH AX N',
    international: 'IH N T ER N AE1 SH AX N AX L',

    // words the rules get right but stress wrong (or nearly right)
    hello: 'HH AX L OW1', hi: 'HH AY1', goodbye: 'G UH D B AY1',
    okay: 'OW K EY1', thanks: 'TH AE1 NG K S', please: 'P L IY1 Z',
    hundred: 'HH AH1 N D R IH D', thousand: 'TH AW1 Z AX N D',
    million: 'M IH1 L Y AX N', billion: 'B IH1 L Y AX N',
    sacred: 'S EY1 K R IH D', wicked: 'W IH1 K IH D', naked: 'N EY1 K IH D',
    study: 'S T AH1 D IY', student: 'S T UW1 D AX N T', duty: 'D UW1 T IY',
    holy: 'HH OW1 L IY', pony: 'P OW1 N IY', ruby: 'R UW1 B IY',
    body: 'B AA1 D IY', copy: 'K AA1 P IY', comedy: 'K AA1 M AX D IY',
    amazing: 'AX M EY1 Z IH NG', around: 'AX R AW1 N D',
    among: 'AX M AH1 NG', amount: 'AX M AW1 N T', apart: 'AX P AA1 R T',
    away: 'AX W EY1', awake: 'AX W EY1 K', aware: 'AX W EH1 R',
    along: 'AX L AO1 NG', alone: 'AX L OW1 N', ago: 'AX G OW1',
    agree: 'AX G R IY1', allow: 'AX L AW1', appear: 'AX P IY1 R',
    arrive: 'AX R AY1 V', attack: 'AX T AE1 K', attempt: 'AX T EH1 M P T',
    attend: 'AX T EH1 N D', avoid: 'AX V OY1 D', across: 'AX K R AO1 S',
    afraid: 'AX F R EY1 D', ability: 'AX B IH1 L IH T IY',
    america: 'AX M EH1 R IH K AX', another_: '',
    begin: 'B IH G IH1 N', began: 'B IH G AE1 N', begun: 'B IH G AH1 N',
    behind: 'B IH HH AY1 N D', believe: 'B IH L IY1 V',
    belong: 'B IH L AO1 NG', below: 'B IH L OW1', beside: 'B IH S AY1 D',
    between: 'B IH T W IY1 N', beyond: 'B IY AA1 N D',
    machine_: '', decide: 'D IH S AY1 D', decision: 'D IH S IH1 ZH AX N',
    depend: 'D IH P EH1 N D', describe: 'D IH S K R AY1 B',
    develop: 'D IH V EH1 L AX P', direct: 'D ER EH1 K T',
    effect: 'IH F EH1 K T', enjoy: 'EH N JH OY1', escape: 'IH S K EY1 P',
    event: 'IH V EH1 N T', except: 'IH K S EH1 P T',
    exist: 'IH G Z IH1 S T', expect: 'IH K S P EH1 K T',
    explain: 'IH K S P L EY1 N', idea_: '',
    imagine: 'IH M AE1 JH IH N', include: 'IH N K L UW1 D',
    increase: 'IH N K R IY1 S', indeed: 'IH N D IY1 D',
    perhaps: 'P ER HH AE1 P S', police: 'P AX L IY1 S',
    potato: 'P AX T EY1 T OW', prepare: 'P R IH P EH1 R',
    receive: 'R IH S IY1 V', record: 'R EH1 K ER D',
    remember: 'R IH M EH1 M B ER', remain: 'R IH M EY1 N',
    repeat: 'R IH P IY1 T', reply: 'R IH P L AY1', report: 'R IH P AO1 R T',
    result: 'R IH Z AH1 L T', return: 'R IH T ER1 N',
    suppose: 'S AX P OW1 Z', support: 'S AX P AO1 R T',
    surprise: 'S ER P R AY1 Z', today: 'T AX D EY1',
    together: 'T AX G EH1 DH ER', tomorrow: 'T AX M AA1 R OW',
    tonight: 'T AX N AY1 T', january: 'JH AE1 N Y UW EH R IY',
    computer: 'K AX M P Y UW1 T ER', internet: 'IH1 N T ER N EH T',
    website: 'W EH1 B S AY T', google: 'G UW1 G AX L',

    quick: 'K W IH1 K', brown: 'B R AW1 N', jumps: 'JH AH1 M P S',
    lazy: 'L EY1 Z IY', dog: 'D AO1 G', fox: 'F AA1 K S'
  };
  ['another_', 'machine_', 'idea_'].forEach(function (k) { delete LEXICON[k]; });

  // Weak (unstressed) forms used when "reduce function words" is on.
  var WEAK = {
    a: 'AX', an: 'AX N', the: 'DH AX', of: 'AX V', to: 'T AX',
    and: 'AX N D', or: 'ER', but: 'B AX T', for: 'F ER', from: 'F R AX M',
    at: 'AX T', as: 'AX Z', than: 'DH AX N', that: 'DH AX T',
    them: 'DH AX M', some: 'S AX M', his: 'HH IH Z', her: 'ER',
    he: 'HH IY', she: 'SH IY', we: 'W IY', you: 'Y UW', your: 'Y ER',
    us: 'AX S', me: 'M IY', be: 'B IY', been: 'B IH N', am: 'AX M',
    are: 'ER', was: 'W AX Z', were: 'W ER', is: 'IH Z', do: 'D AX',
    does: 'D AX Z', can: 'K AX N', could: 'K AX D', would: 'W AX D',
    should: 'SH AX D', must: 'M AX S T', have: 'HH AX V', has: 'HH AX Z',
    had: 'HH AX D', will: 'W AX L', shall: 'SH AX L', there: 'DH ER',
    with: 'W IH DH', just: 'JH AX S T'
  };

  // ------------------------------------------------------------------ rules
  var RULES = {
    A: [
      ' [A] =AX',
      ' [ARE] =AA R',
      ' [AR]O=AX R',
      '[ARI]#=EH R IY',
      '[AR]E=EH R',
      '[AR]Y=EH R',
      '[AR]#=AE R',
      ' ^[AS]#=EY S',
      '[A]WA=AX',
      '[AW]=AO',
      ' :[ANY]=EH N IY',
      '[A]^+#=EY',
      '#:[ALLY]=AX L IY',
      ' [AL]#=AX L',
      '[AGAIN]=AX G EH N',
      '#:[AG]E=IH JH',
      '[A]^%=EY',
      '[A]^+:#=AE',
      ' :[A]^+ =EY',
      '[ARR] =AX R',
      '[ARR]=AE R',
      ' [AR] =AA R',
      '#:[AR] =ER',
      '[AR]=AA R',
      '[AIR]=EH R',
      '[AI]=EY',
      '[AY]=EY',
      '[AU]=AO',
      '#:[AL] =AX L',
      '#:[ALS] =AX L Z',
      '[ALK]=AO K',
      '[A]L^=AO',
      ' :[ABLE]=EY B AX L',
      '[ABLE]=AX B AX L',
      '[ANG]+=EY N JH',
      '[AA]=AA',
      '[A]=AE'
    ],
    B: [
      ' [BE]^#=B IH',
      '[BEING]=B IY IH NG',
      ' [BOTH] =B OW TH',
      ' [BUS]#=B IH Z',
      '[BUIL]=B IH L',
      '[BB]=B',
      '[B]=B'
    ],
    C: [
      ' [CH]^=K',
      '^E[CH]=K',
      '[CHR]=K R',
      '[CH]=CH',
      ' S[CI]#=S AY',
      '[CI]A=SH',
      '[CI]O=SH',
      '[CI]EN=SH',
      '[CC]+=K S',
      '[CC]=K',
      '[CK]=K',
      '[COM]%=K AH M',
      '[C]+=S',
      '[C]=K'
    ],
    D: [
      '#:[DED] =D IH D',
      '.E[D] =D',
      '#^:E[D] =T',
      ' [DE]^#=D IH',
      ' [DO] =D UW',
      ' [DOES]=D AH Z',
      ' [DOING]=D UW IH NG',
      ' [DOW]=D AW',
      '[DU]A=JH UW',
      '[DG]+=JH',
      '[DD]=D',
      '[D]=D'
    ],
    E: [
      '#:[E] =',
      "'^:[E] =",
      ' :[E] =IY',
      '#[ED] =D',
      '#:[E]D =',
      '[EV]ER=EH V',
      '[E]^%=IY',
      '[ERI]#=IY R IY',
      '[ERI]=EH R IH',
      '#:[ER]#=ER',
      '[ER]#=EH R',
      '[ER]=ER',
      ' [EVEN]=IY V EH N',
      '#:[E]W=',
      '@[EW]=UW',
      '[EW]=Y UW',
      '[E]O=IY',
      '#:&[ES] =IH Z',
      '#:[E]S =',
      '#:[ELY] =L IY',
      '#:[EMENT]=M EH N T',
      '[EFUL]=F UH L',
      '[EE]=IY',
      '[EARN]=ER N',
      ' [EAR]^=ER',
      '[EAD]=EH D',
      '#:[EA] =IY AX',
      '[EA]SU=EH',
      '[EA]=IY',
      '[EIGH]=EY',
      '[EI]=IY',
      ' [EYE]=AY',
      '[EY]=IY',
      '[EU]=Y UW',
      '[E]=EH'
    ],
    F: [
      '[FUL]=F UH L',
      '[FF]=F',
      '[F]=F'
    ],
    G: [
      '[GIV]=G IH V',
      ' [G]I^=G',
      '[GE]T=G EH',
      'SU[GGES]=G JH EH S',
      '[GG]=G',
      ' B#[G]=G',
      '[G]+=JH',
      '[GREAT]=G R EY T',
      '#[GH]=',
      ' [GN]=N',
      '[G]=G'
    ],
    H: [
      ' [HAV]=HH AE V',
      ' [HERE]=HH IY R',
      ' [HOUR]=AW ER',
      '[HOW]=HH AW',
      '[H]#=HH',
      '[H]='
    ],
    I: [
      ' [I] =AY',
      ' [IN]=IH N',
      '[I] =AY',
      '[ITY]=IH T IY',
      ' ^[I]O=AY',
      '[IN]D=AY N',
      '[IER]=IY ER',
      '#:R[IED] =IY D',
      '[IED] =AY D',
      '[IEN]=IY EH N',
      '[IE]T=AY EH',
      ' :[I]%=AY',
      '[I]%=IY',
      '[IE]=IY',
      '[I]^+:#=IH',
      '[IR]#=AY R',
      '[IZ]%=AY Z',
      '[IS]%=AY Z',
      '[I]D%=AY',
      '+^[I]^+=IH',
      '[I]T%=AY',
      '#:^[I]^+=IH',
      '[I]^+=AY',
      '[IR]=ER',
      '[IGH]=AY',
      '[ILD]=AY L D',
      '[IGN] =AY N',
      '[IGN]^=AY N',
      '[IGN]%=AY N',
      '[IQUE]=IY K',
      '[I]=IH'
    ],
    J: ['[J]=JH'],
    K: [' [K]N=', '[KK]=K', '[K]=K'],
    L: [
      '[LO]C#=L OW',
      'L[L]=',
      '#^:[L]%=AX L',
      '[LEAD]=L IY D',
      '[L]=L'
    ],
    M: ['[MOV]=M UW V', '[MM]=M', '[M]=M'],
    N: [
      'E[NG]+=N JH',
      '[NG]R=NG G',
      '[NG]#=NG G',
      '[NGL]%=NG G AX L',
      '[NG]=NG',
      '[NK]=NG K',
      ' [NOW] =N AW',
      '[NN]=N',
      '[N]=N'
    ],
    O: [
      '[OF] =AX V',
      '[OROUGH]=ER OW',
      '#:[OR] =ER',
      '#:[ORS] =ER Z',
      '[OR]=AO R',
      ' [ONE]=W AH N',
      '[OW]=OW',
      ' [OVER]=OW V ER',
      '[OV]=AH V',
      '[O]^%=OW',
      '[O]^EN=OW',
      '[O]^I#=OW',
      '[OL]D=OW L',
      '[OUGHT]=AO T',
      '[OUGH]=AH F',
      ' [OU]=AW',
      'H[OU]S#=AW',
      '[OUS]=AX S',
      '[OUR]=AO R',
      '[OULD]=UH D',
      '^[OU]^L=AH',
      '[OUP]=UW P',
      '[OU]=AW',
      '[OY]=OY',
      '[OING]=OW IH NG',
      '[OI]=OY',
      '[OOR]=AO R',
      '[OOK]=UH K',
      '[OOD]=UH D',
      '[OO]=UW',
      '[O]E=OW',
      '[O] =OW',
      '[OA]=OW',
      ' [ONLY]=OW N L IY',
      ' [ONCE]=W AH N S',
      "[ON'T]=OW N T",
      'C[O]N=Q',
      '[O]NG=AO',
      ' :^[O]N=AH',
      'I[ON]=AX N',
      '#:[ON] =AX N',
      '#^[ON]=AX N',
      '[O]ST =OW',
      '[OF]^=AO F',
      '[OTHER]=AH DH ER',
      '[OSS] =AO S',
      '#^:[OM]=AH M',
      '[O]=Q'
    ],
    P: [
      '[PH]=F',
      '[PEOP]=P IY P',
      '[POW]=P AW',
      '[PUT] =P UH T',
      ' [PN]=N',
      ' [PS]=S',
      '[PP]=P',
      '[P]=P'
    ],
    Q: ['[QUAR]=K W AO R', '[QU]=K W', '[Q]=K'],
    R: [' [RE]^#=R IY', '[RR]=R', '[R]=R'],
    S: [
      '[SH]=SH',
      '#[SION]=ZH AX N',
      '[SOME]=S AH M',
      '#[SUR]#=ZH ER',
      '[SUR]#=SH ER',
      '#[SSU]#=SH UW',
      '#[SU]#=ZH UW',
      '#[SED] =Z D',
      '#[S]#=Z',
      '[SAID]=S EH D',
      '^[SION]=SH AX N',
      '[S]S=',
      '.[S] =Z',
      '#:.E[S] =Z',
      '#^:#[S] =S',
      'U[S] =S',
      ' :#[S] =Z',
      ' [SCH]=S K',
      '[S]C+=',
      '#[SM]=Z M',
      "#[SN]'=Z AX N",
      '[S]=S'
    ],
    T: [
      ' [THE] =DH AX',
      '[TO] =T UW',
      '[THAT] =DH AE T',
      ' [THIS] =DH IH S',
      ' [THEY]=DH EY',
      ' [THERE]=DH EH R',
      '[THER]=DH ER',
      '[THEIR]=DH EH R',
      ' [THAN] =DH AE N',
      ' [THEM] =DH EH M',
      '[THESE] =DH IY Z',
      ' [THEN]=DH EH N',
      '[THROUGH]=TH R UW',
      '[THOSE]=DH OW Z',
      '[THOUGH] =DH OW',
      ' [THUS]=DH AH S',
      '[TCH]=CH',
      '[TH]=TH',
      '#:[TED] =T IH D',
      'S[TI]#N=CH',
      '[TI]O=SH',
      '[TI]A=SH',
      '[TIEN]=SH AX N',
      '[TUR]#=CH ER',
      '[TU]A=CH UW',
      ' [TWO]=T UW',
      '[TT]=T',
      '[T]=T'
    ],
    U: [
      ' [UN]I=Y UW N',
      ' [UN]=AH N',
      ' [UPON]=AX P AO N',
      '@[UR]#=UH R',
      '[UR]#=Y UH R',
      '[UR]=ER',
      '[U]^ =AH',
      '[U]^^=AH',
      '[UY]=AY',
      ' G[U]#=',
      'G[U]%=W',
      'G[U]#=W',
      '#N[U]=Y UW',
      '@[U]=UW',
      '[U]=Y UW'
    ],
    V: ['[VIEW]=V Y UW', '[V]=V'],
    W: [
      ' [WERE]=W ER',
      '[WA]SH=W AA',
      '[WA]S=W AA',
      '[WA]T=W AA',
      '[WHERE]=W EH R',
      '[WHAT]=W AH T',
      '[WHOL]=HH OW L',
      '[WHO]=HH UW',
      '[WH]=W',
      '[WAR]=W AO R',
      '[WOR]^=W ER',
      '[WR]=R',
      '[W]=W'
    ],
    X: [' [X]=Z', '[X]=K S'],
    Y: [
      '[YOUNG]=Y AH NG',
      ' [YOU]=Y UW',
      ' [YES]=Y EH S',
      ' [Y]=Y',
      '#^:[Y] =IY',
      '#^:[Y]I=IY',
      ' :[Y] =AY',
      ' :[Y]#=AY',
      ' :[Y]^+:#=IH',
      ' :[Y]^#=AY',
      '[Y]=IH'
    ],
    Z: ['[ZZ]=Z', '[Z]=Z']
  };

  /* ------------------------------------------------------------ homophones
   * Groups of words that sound alike, for the sound-alike notation. Kept to
   * pairs that hold in most accents — merry/marry/Mary and caught/court are
   * left out because they only rhyme in some of them. */
  var HOMOPHONES = [
    ['time', 'thyme'], ['to', 'too', 'two'], ['there', 'their', "they're"],
    ['right', 'write', 'rite', 'wright'], ['night', 'knight'],
    ['know', 'no'], ['knew', 'new', 'gnu'], ['our', 'hour'],
    ['hear', 'here'], ['hair', 'hare'], ['bare', 'bear'],
    ['pair', 'pear', 'pare'], ['flour', 'flower'], ['flee', 'flea'],
    ['see', 'sea'], ['be', 'bee'], ['by', 'buy', 'bye'], ['i', 'eye', 'aye'],
    ['one', 'won'], ['son', 'sun'], ['sail', 'sale'], ['tail', 'tale'],
    ['made', 'maid'], ['mail', 'male'], ['main', 'mane'],
    ['meat', 'meet', 'mete'], ['need', 'knead'], ['nose', 'knows'],
    ['not', 'knot'], ['hole', 'whole'], ['holy', 'wholly'],
    ['weak', 'week'], ['wait', 'weight'], ['waste', 'waist'],
    ['way', 'weigh', 'whey'], ['wear', 'ware'], ['weather', 'whether'],
    ['which', 'witch'], ['wood', 'would'], ['break', 'brake'],
    ['cell', 'sell'], ['cent', 'scent', 'sent'], ['cereal', 'serial'],
    ['chews', 'choose'], ['coarse', 'course'], ['creak', 'creek'],
    ['dear', 'deer'], ['die', 'dye'], ['fair', 'fare'], ['feat', 'feet'],
    ['find', 'fined'], ['for', 'four', 'fore'], ['foul', 'fowl'],
    ['grate', 'great'], ['groan', 'grown'], ['heal', 'heel', "he'll"],
    ['heard', 'herd'], ['heir', 'air'], ['hi', 'high'],
    ['hoarse', 'horse'], ['idle', 'idol'], ['in', 'inn'], ['its', "it's"],
    ['jeans', 'genes'], ['lead', 'led'], ['leak', 'leek'],
    ['lessen', 'lesson'], ['liar', 'lyre'], ['loan', 'lone'],
    ['maize', 'maze'], ['mall', 'maul'], ['medal', 'meddle'],
    ['might', 'mite'], ['mind', 'mined'], ['miner', 'minor'],
    ['missed', 'mist'], ['moan', 'mown'], ['moose', 'mousse'],
    ['morning', 'mourning'], ['muscle', 'mussel'], ['naval', 'navel'],
    ['none', 'nun'], ['oar', 'or', 'ore'], ['pail', 'pale'],
    ['pain', 'pane'], ['passed', 'past'], ['patience', 'patients'],
    ['pause', 'paws'], ['peace', 'piece'], ['peak', 'peek', 'pique'],
    ['peal', 'peel'], ['pedal', 'peddle'], ['peer', 'pier'],
    ['plain', 'plane'], ['pole', 'poll'], ['poor', 'pour', 'pore'],
    ['praise', 'prays', 'preys'], ['presence', 'presents'],
    ['pride', 'pried'], ['principal', 'principle'], ['profit', 'prophet'],
    ['rain', 'reign', 'rein'], ['raise', 'rays', 'raze'], ['rap', 'wrap'],
    ['read', 'reed'], ['real', 'reel'], ['ring', 'wring'],
    ['road', 'rode', 'rowed'], ['role', 'roll'], ['root', 'route'],
    ['rose', 'rows'], ['rough', 'ruff'], ['rung', 'wrung'],
    ['scene', 'seen'], ['seam', 'seem'], ['seas', 'sees', 'seize'],
    ['sight', 'site', 'cite'], ['slay', 'sleigh'], ['soar', 'sore'],
    ['sole', 'soul'], ['some', 'sum'], ['stair', 'stare'],
    ['stake', 'steak'], ['stationary', 'stationery'], ['steal', 'steel'],
    ['straight', 'strait'], ['suite', 'sweet'], ['tacks', 'tax'],
    ['taught', 'taut'], ['tea', 'tee'], ['team', 'teem'], ['tear', 'tier'],
    ['threw', 'through'], ['throne', 'thrown'], ['tide', 'tied'],
    ['toad', 'towed', 'toed'], ['toe', 'tow'], ['told', 'tolled'],
    ['vain', 'vane', 'vein'], ['vary', 'very'], ['wail', 'whale'],
    ['waive', 'wave'], ['war', 'wore'], ['warn', 'worn'], ['we', 'wee'],
    ['wet', 'whet'], ['wine', 'whine'], ['yoke', 'yolk'],
    ['you', 'ewe', 'yew'], ['your', "you're", 'yore'],
    ['aloud', 'allowed'], ['ate', 'eight'], ['aunt', 'ant'],
    ['bail', 'bale'], ['ball', 'bawl'], ['band', 'banned'],
    ['bass', 'base'], ['beach', 'beech'], ['beat', 'beet'],
    ['berry', 'bury'], ['berth', 'birth'], ['billed', 'build'],
    ['blew', 'blue'], ['boar', 'bore'], ['board', 'bored'],
    ['bold', 'bowled'], ['border', 'boarder'], ['bough', 'bow'],
    ['boy', 'buoy'], ['bread', 'bred'], ['brews', 'bruise'],
    ['bridal', 'bridle'], ['but', 'butt'], ['cast', 'caste'],
    ['ceiling', 'sealing'], ['chord', 'cord'], ['clause', 'claws'],
    ['colonel', 'kernel'], ['council', 'counsel'], ['cue', 'queue'],
    ['currant', 'current'], ['cymbal', 'symbol'], ['days', 'daze'],
    ['dew', 'due'], ['doe', 'dough'], ['dual', 'duel'], ['earn', 'urn'],
    ['fate', 'fete'], ['faze', 'phase'], ['fir', 'fur'],
    ['flair', 'flare'], ['flew', 'flu', 'flue'], ['floe', 'flow'],
    ['gait', 'gate'], ['gilt', 'guilt'], ['gorilla', 'guerrilla'],
    ['guessed', 'guest'], ['hall', 'haul'], ['hangar', 'hanger'],
    ['hay', 'hey'], ['heroin', 'heroine'], ['hew', 'hue'],
    ['higher', 'hire'], ['him', 'hymn'], ['hoard', 'horde'],
    ['knit', 'nit'], ['lain', 'lane'], ['laps', 'lapse'], ['lay', 'lei'],
    ['leach', 'leech'], ['lie', 'lye'], ['links', 'lynx'],
    ['loot', 'lute'], ['manner', 'manor'], ['mantel', 'mantle'],
    ['metal', 'mettle'], ['moat', 'mote'], ['mode', 'mowed'],
    ['mourn', 'morn'], ['pact', 'packed'], ['pea', 'pee'],
    ['pi', 'pie'], ['pistil', 'pistol'], ['place', 'plaice'],
    ['pleas', 'please'], ['plum', 'plumb'], ['pray', 'prey'],
    ['racket', 'racquet'], ['rapped', 'rapt', 'wrapped'], ['red', 'read'],
    ['reek', 'wreak'], ['rest', 'wrest'], ['retch', 'wretch'],
    ['review', 'revue'], ['rime', 'rhyme'], ['rye', 'wry'],
    ['sac', 'sack'], ['scull', 'skull'], ['seller', 'cellar'],
    ['serf', 'surf'], ['sew', 'so', 'sow'], ['shear', 'sheer'],
    ['shoe', 'shoo'], ['side', 'sighed'], ['sighs', 'size'],
    ['sign', 'sine'], ['sink', 'sync'], ['slight', 'sleight'],
    ['sloe', 'slow'], ['soared', 'sword'], ['sold', 'soled'],
    ['staid', 'stayed'], ['step', 'steppe'], ['stile', 'style'],
    ['storey', 'story'], ['sundae', 'sunday'], ['taper', 'tapir'],
    ['tense', 'tents'], ['tern', 'turn'], ['tic', 'tick'],
    ['timber', 'timbre'], ['ton', 'tun'], ['tough', 'tuff'],
    ['tracked', 'tract'], ['troop', 'troupe'], ['trussed', 'trust'],
    ['vale', 'veil'], ['vice', 'vise'], ['wade', 'weighed'],
    ['wain', 'wane'], ['ward', 'warred'], ['weal', 'wheel'],
    ['weld', 'welled'], ['whig', 'wig'], ['while', 'wile'],
    ['whither', 'wither'], ["who's", 'whose'], ['worst', 'wurst'],
    ["you'll", 'yule'], ['air', 'ere'], ['allowed', 'aloud'],
    ['altar', 'alter'], ['arc', 'ark'], ['bait', 'bate'],
    ['bald', 'bawled'], ['bard', 'barred'], ['baron', 'barren'],
    ['bazaar', 'bizarre'], ['beau', 'bow'], ['bloc', 'block'],
    ['boarder', 'border'], ['brake', 'break'], ['bussed', 'bust'],
    ['canvas', 'canvass'], ['capital', 'capitol'], ['cite', 'site'],
    ['climb', 'clime'], ['course', 'coarse'], ['crews', 'cruise'],
    ['discreet', 'discrete'], ['dyeing', 'dying'], ['ewes', 'use'],
    ['flair', 'flare'], ['forth', 'fourth'], ['gene', 'jean'],
    ['gnaw', 'nor'], ['grisly', 'grizzly'], ['groan', 'grown'],
    ['hoes', 'hose'], ['knap', 'nap'], ['knave', 'nave'],
    ['knob', 'nob'], ['lessen', 'lesson'], ['lynx', 'links'],
    ['mask', 'masque'], ['mews', 'muse'], ['mucous', 'mucus'],
    ['pare', 'pear'], ['pearl', 'purl'], ['pedal', 'petal'],
    ['pole', 'poll'], ['rack', 'wrack'], ['raiser', 'razor'],
    ['seal', 'seel'], ['seine', 'sane'], ['sonny', 'sunny'],
    ['succor', 'sucker'], ['tare', 'tear'], ['team', 'teem'],
    ['their', 'there'], ['tighten', 'titan'], ['vain', 'vein'],
    ['waist', 'waste'], ["we'll", 'wheel'], ["we're", 'weir'],
    ['whined', 'wind'], ['wood', 'would']
  ];

  /* ---------------------------------------------------------- typo endings
   * Word endings English itself can't keep straight, as [written, mistyped]
   * pairs. Both directions are listed because both are typed. Nothing here is
   * trusted on its own — the typo mode sounds every candidate out and throws
   * away any that changes the pronunciation, so a pair that only works on
   * some words (tion/sion) costs nothing to list. */
  var TYPO_SUFFIX = [
    ['ance', 'ence'], ['ence', 'ance'], ['ant', 'ent'], ['ent', 'ant'],
    ['able', 'ible'], ['ible', 'able'], ['ably', 'ibly'], ['ibly', 'ably'],
    ['ary', 'ery'], ['ery', 'ary'], ['ory', 'ary'], ['ery', 'ory'],
    ['ise', 'ize'], ['ize', 'ise'], ['yse', 'yze'], ['yze', 'yse'],
    ['our', 'or'], ['or', 'our'], ['or', 'er'], ['er', 'or'],
    ['re', 'er'], ['er', 're'], ['ce', 'se'], ['se', 'ce'],
    ['cy', 'sy'], ['sy', 'cy'], ['sion', 'tion'], ['tion', 'sion'],
    ['ey', 'y'], ['y', 'ey'], ['ie', 'y'], ['ffe', 'ff'], ['gue', 'g']
  ];

  /* Grapheme options for inventing a fresh spelling when no homophone exists.
   * First choice is always the plainest one, which is what gives the mode its
   * simplified-spelling look: nite, skool, fone, laf. Vowels differ depending
   * on whether the syllable is open (no coda) or closed; "a_e" means a magic
   * e goes on the end of the syllable. */
  var ONSET_SPELL = {
    B: ['b'], CH: ['ch'], D: ['d'], DH: ['th'], F: ['f', 'ph'],
    G: ['g', 'gh'], HH: ['h'], JH: ['j', 'g'], K: ['k', 'c', 'ch'],
    L: ['l'], M: ['m'], N: ['n', 'kn', 'gn'], NG: ['ng'], P: ['p'],
    R: ['r', 'wr', 'rh'], S: ['s', 'c', 'ps'], SH: ['sh', 'ch'], T: ['t'],
    TH: ['th'], V: ['v'], W: ['w', 'wh'], WH: ['wh', 'w'], Y: ['y'],
    Z: ['z'], ZH: ['zh', 'j']
  };
  var CODA_SPELL = {
    B: ['b', 'bb'], CH: ['ch', 'tch'], D: ['d', 'dd'], DH: ['the'],
    F: ['f', 'ff', 'gh', 'ph'], G: ['g', 'gg'], HH: ['h'],
    JH: ['ge', 'dge'], K: ['k', 'ck', 'c', 'que'], L: ['l', 'll', 'le'],
    M: ['m', 'mm', 'mb'], N: ['n', 'nn'], NG: ['ng'], P: ['p', 'pp'],
    R: ['r', 'rr'], S: ['s', 'ss', 'ce'], SH: ['sh'], T: ['t', 'tt'],
    TH: ['th'], V: ['v', 've'], W: ['w'], Y: ['y'], Z: ['z', 's', 'zz'],
    ZH: ['ge']
  };
  var VOWEL_SPELL = {
    IY: { o: ['ee', 'ea', 'y'], c: ['ee', 'ea', 'e_e'] },
    IH: { o: ['i', 'y'], c: ['i', 'y'] },
    EY: { o: ['ay', 'ey'], c: ['a_e', 'ai', 'ay'] },
    EH: { o: ['e', 'eh'], c: ['e', 'ea'] },
    AE: { o: ['a'], c: ['a'] },
    AY: { o: ['y', 'ie', 'igh'], c: ['i_e', 'igh', 'y'] },
    AA: { o: ['ah', 'a'], c: ['o', 'a'] },
    Q: { o: ['o'], c: ['o', 'a'] },
    AO: { o: ['aw'], c: ['au', 'aw', 'o'] },
    AH: { o: ['u'], c: ['u', 'o'] },
    AX: { o: ['uh', 'a', 'u'], c: ['u', 'a', 'e'] },
    OW: { o: ['o', 'oh', 'ow'], c: ['o_e', 'oa', 'ow'] },
    UH: { o: ['oo'], c: ['oo', 'u'] },
    UW: { o: ['oo', 'ew', 'ue'], c: ['oo', 'u_e', 'ew'] },
    AW: { o: ['ow'], c: ['ou', 'ow'] },
    OY: { o: ['oy'], c: ['oi', 'oy'] },
    ER: { o: ['er', 'ur'], c: ['er', 'ur', 'ir'] },
    IX: { o: ['y', 'i'], c: ['i', 'e'] }
  };

  // ------------------------------------------------------- number expansion
  var ONES = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven',
    'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen',
    'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen'];
  var TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty',
    'seventy', 'eighty', 'ninety'];
  var SCALES = [
    [1e12, 'trillion'], [1e9, 'billion'], [1e6, 'million'], [1e3, 'thousand']
  ];

  root.IPA_DATA = {
    LEXICON: LEXICON,
    WEAK: WEAK,
    RULES: RULES,
    HOMOPHONES: HOMOPHONES,
    TYPO_SUFFIX: TYPO_SUFFIX,
    ONSET_SPELL: ONSET_SPELL,
    CODA_SPELL: CODA_SPELL,
    VOWEL_SPELL: VOWEL_SPELL,
    ONES: ONES,
    TENS: TENS,
    SCALES: SCALES
  };
})(typeof window !== 'undefined' ? window : this);
